services:
  db-book:
    image: mysql:8
    restart: always
    env_file:
      - ./env_files/db-book.env
    ports:
      - "3310:3306"
    networks:
      - neves-network
    volumes:
      - mysql-volume-book:/var/lib/mysql

  db-exchange:
    image: mysql:8
    restart: always
    env_file:
      - ./env_files/db-exchange.env
    ports:
      - "3311:3306"
    networks:
      - neves-network
    volumes:
      - mysql-volume-exchange:/var/lib/mysql


  book-service:
    image: arturnevesalmeida/book-service
    restart: always
    build:
      context: ./book-service
      dockerfile: Dockerfile
    ports:
      - 8100:8100
    env_file:
      - ./env_files/.env
      - ./env_files/book.env
    depends_on:
      - db-book
    networks:
      - neves-network

  exchange-service:
    image: arturnevesalmeida/exchange-service
    restart: always
    build:
      context: ./exchange-service
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    env_file:
      - ./env_files/.env
      - ./env_files/exchange.env
    depends_on:
      - db-exchange
    networks:
      - neves-network

networks:
  neves-network:
    name: neves-network
    driver: bridge

volumes:
  mysql-volume-book:
    driver: local
  mysql-volume-exchange:
    driver: local
