apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: exchange-service
  name: exchange-service
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: exchange-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: exchange-service
    spec:
      containers:
        - name: exchange-service
          image: arturnevesalmeida/exchange-service:kube-V1
          imagePullPolicy: IfNotPresent
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: exchange-service
  name: exchange-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 8100
      targetPort: 8100
      protocol: TCP
  selector:
    app: exchange-service
