name: Microsservices Continuos Deployment with Git

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: bookrate_envs

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Update submodules
      run: git submodule update --init --recursive
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt' 

    - name: Build Eureka Server Docker Image 
      working-directory: ./eureka-server
      run: mvn spring-boot:build-image -DskipTests  

    - name: Build Api Gateway Server Docker Image
      working-directory: ./api-gateway
      run: mvn spring-boot:build-image -DskipTests
