name: Microsservices Continuos Deployment with Git

on:
  push:
    branches: [ "branch-update-config-with-kubernetes" ]
  pull_request:
    branches: [ "branch-update-config-with-kubernetes" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: bookrate_envs

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Update submodules
      run: git submodule update --init --recursive
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt' 

    - name: Build Book Service Docker Image
      working-directory: ./book-service
      run: mvn clean package

    - name: Build Exchange Service Docker Image
      working-directory: ./exchange-service
      run: mvn clean package
      
    - name: Docker compose build
      run: docker compose build

    - name: Tag Docker Images
      run: |
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/book-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/book-service:${{github.RUN_ID}}
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/book-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/book-service:kube-V1
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/exchange-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/exchange-service:${{github.RUN_ID}}
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/exchange-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/exchange-service:kube-V1

    - name: Push Docker Images to Docker Hub
      run: |
        docker push ${{secrets.DOCKERHUB_USERNAME}}/book-service:latest
        docker push ${{secrets.DOCKERHUB_USERNAME}}/book-service:kube-V1
        docker push ${{secrets.DOCKERHUB_USERNAME}}/book-service:${{github.RUN_ID}}
        docker push ${{secrets.DOCKERHUB_USERNAME}}/exchange-service:latest
        docker push ${{secrets.DOCKERHUB_USERNAME}}/exchange-service:kube-V1
        docker push ${{secrets.DOCKERHUB_USERNAME}}/exchange-service:${{github.RUN_ID}}
        
