name: Microsservices Continuos Deployment with Git

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: bookrate_envs

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Update submodules
      run: git submodule update --init --recursive
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt' 

    - name: Build Eureka Server Docker Image 
      working-directory: ./eureka-server
      run: mvn spring-boot:build-image  

    - name: Build Api Gateway Server Docker Image
      working-directory: ./api-gateway
      run: mvn spring-boot:build-image 

    - name: Build Book Service Docker Image
      working-directory: ./book-service
      run: mvn clean package

    - name: Build Exchange Service Docker Image
      working-directory: ./exchange-service
      run: mvn clean package
      
    - name: Docker compose build
      run: docker compose build

    - name: Tag Docker Images
      run: |
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/eureka-server:0.0.1-SNAPSHOT ${{ secrets.DOCKERHUB_USERNAME }}/eureka-server:latest
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/eureka-server:0.0.1-SNAPSHOT ${{ secrets.DOCKERHUB_USERNAME }}/eureka-server:${{github.RUN_ID}}
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:0.0.1-SNAPSHOT ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:0.0.1-SNAPSHOT ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:${{github.RUN_ID}}
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/book-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/book-service:${{github.RUN_ID}}
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/exchange-service:latest ${{ secrets.DOCKERHUB_USERNAME }}/exchange-service:${{github.RUN_ID}}

    - name: Push Docer Images to Docker Hub
      run: |
        docker push ${{secrets.DOCKERHUB_USERNAME}}/api-gateway:latest
        docker push ${{secrets.DOCKERHUB_USERNAME}}/api-gateway:${{github.RUN_ID}}
        docker push ${{secrets.DOCKERHUB_USERNAME}}/eureka-server:latest
        docker push ${{secrets.DOCKERHUB_USERNAME}}/eureka-server:${{github.RUN_ID}}
        docker push ${{secrets.DOCKERHUB_USERNAME}}/book-service:latest
        docker push ${{secrets.DOCKERHUB_USERNAME}}/book-service:${{github.RUN_ID}}
        docker push ${{secrets.DOCKERHUB_USERNAME}}/exchange-service:latest
        docker push ${{secrets.DOCKERHUB_USERNAME}}/exchange-service:${{github.RUN_ID}}
        
