name: Microsservices Continuos Deployment with Git

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup Java 21
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt' 

    - name: Build Eureka Naming Server Docker Image 
      working-directory: ./exchange-service
      run: mvn spring-boot:build-image -DskipTests
